check for puppet.d module existance

diff --git a/jail/cbsdpuppetsrv/CBSDfile b/jail/cbsdpuppetsrv/CBSDfile
--- a/jail/cbsdpuppetsrv/CBSDfile
+++ b/jail/cbsdpuppetsrv/CBSDfile
@@ -1,5 +1,23 @@
 quiet=0
 
+
+preup()
+{
+	# check for puppet.d module existance
+	if [ ! -d /usr/local/cbsd/modules/puppet.d/modules/public/stdlib ]; then
+		${ECHO} "${W1_COLOR}preup function failed:${N0_COLOR}"
+		echo
+		${ECHO} "${N1_COLOR}  This environment depends on the presence of the ${N2_COLOR}puppet${N1_COLOR} module.${N0_COLOR}"
+		${ECHO} "${N1_COLOR}  Please install and activate it:${N0_COLOR}"
+		echo
+		${ECHO} "${N2_COLOR}    cbsd module mode=install puppet${N0_COLOR}"
+		${ECHO} "${N2_COLOR}    echo 'puppet.d' >> ~cbsd/etc/modules.conf${N0_COLOR}"
+		${ECHO} "${N2_COLOR}    cbsd initenv${N0_COLOR}"
+		echo
+		exit 1
+	fi
+}
+
 jail_cbsdpuppetsrv()
 {
 	ip4_addr="DHCP"
